#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
#

#
# Gradle start up script for POSIX generated by Gradle.
# This file is generated once and kept on the file system.
#

APP_HOME=$(cd -- "$(dirname -- "$0")" >/dev/null 2>&1 && pwd)
APP_NAME="Gradle App"
APP_BASE_NAME=${0##*/}

# Attempt to set APP_HOME with a native path. The `dirname` on this line
# fails only when it's inside a `CONDA`- or `VENV`-activated shell.
if [ "$*" = "" ] ; then
  APP_HOME=""
fi

# Use GNU echo if available
if command -v gecho >/dev/null 2>&1; then
  ECHO="gecho"
else
  ECHO="echo"
fi

JAVACMD="java"
if [ -n "$JAVA_HOME" ] && [ -x "$JAVA_HOME/bin/java" ]; then
  JAVACMD="$JAVA_HOME/bin/java"
fi

if [ -f "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" ]; then
  CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"
else
  $ECHO "Gradle wrapper jar not found at $APP_HOME/gradle/wrapper/gradle-wrapper.jar"
  exit 1
fi

exec "$JAVACMD" $JAVA_OPTS $DEFAULT_JVM_OPTS $APP_HOME/gradle/wrapper/gradle-wrapper.jar "$@"